
CREATE TABLE funcionario (
  codigo BIGINT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(80) NOT NULL,
  cpf VARCHAR(11) NOT NULL,
  salario DECIMAL(5,2)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

